### PR TITLE
🔒🐛 Improve gateway handling

### LINKED ISSUE #132: 🔒🐛 Using Mixed ExclusiveGateway Types causes unpredictable behavior
#### Describe your issue

There are 4 possible types of `ExclusiveGateways` that the parser can currently recognize
- Split: A gateway has more outgoing sequence flows than incoming
- Join: A gateway has more incoming sequence flows than outgoing
- Mixed: The number of outgoing and incoming sequence flows is identical
- Undefined: The type of the gateway is indetermined. This usually happens, if no incoming and/or no outgoing Sequence Flows have been assigned to the Gateway

Using Mixed `ExclusiveGateways` is not supported at all.

Undefined `ExclusiveGateways` are ignored and are thus prone to causing non-descriptive runtime errors, like `Cannot read ID of undefined`.

Right now we have only implemented the first two scenarios in a very basic way.

**Basic Split Gateway**

A Split-Gateway will always pick the first outgoing SequenceFlow that has a truthy condition. If additional SequenceFlows have truthy conditions, they are ignored. 

This UseCase should actually cause an Error, because how are we to know which one of the truthy paths the User intended the ProcessInstance to take?
Just taking the first SequenceFlow whose condition matched could be dangerous (what if taking that path is not intended and leads to a task named `Launch nuclear missile`?)

**Basic Join Gateway**

This type of Gateway always assumes that only one outgoing SequenceFlow is present and is executed as such.

If there really is only one outgoing SequenceFlow, this is no problem. 

But if we have, say, 3 incoming and 2 outgoing SequenceFlows, the Gateway will assume that it is a "Join" Gateway and just pick a SequenceFlow at random with which to continue.
This is because the Join-Gateway doesn't evaluate any possible conditions on the outgoing SequenceFlows.

This results in completely unpredictable and possibly dangerous behavior (i.e. starting a nuclear war). 

There are two options on how we can handle this:
a) Treat the Gateway as Split-Gateway, forcing it to evaluate the outgoing SequenceFlows assigned Conditions again. This would effectively cover the `MixedGateway` UseCase as well.
b) Throw an error. 

**NOTE:**
This is an issue with Parallel Gateways as well. 

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

## Example

<details>
<summary>
:warning: Before creating the issue, click here to expand and follow the guide.
</summary>
<br>
  
1. Be sure to fill out **every** topic presented in this template. 
If a section is not valid or useful for your issue, feel free to remove it.

2. Use the attached Checklist to make sure your issue contains all relevant information.

3. Attach a label to your issue that reflects what your issue is all about.
**When your issue concerns only a specific platform, be sure to attach the label for that platform!**

4. Please use a fitting emoji at the beginning of your issue title.

Example 1 - Report a bug:
```md
:bug: Something is not working properly
```

Example 2 - Report a performance issue:
```md
:zap: Something is slower than it should be
```

Example 3 - Report a package vulnerability or security issue:
```md
:lock: Package xy produces vulnerabilites
```

```md
:lock: User XY has access to something he shouldn't have
```

Example 4 - Report missing test coverage: 
```md
:white_check_mark: Add tests for...
```

You can of course phrase your titles however you like.
Just be sure they are short, to the point and convey the general idea of the issue you are experiencing.
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your Issue with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️     |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️     |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### PR DESCRIPTION
**Pull request by ElRaptorus**
Requires:
process-engine/process_engine_contracts#78
process-engine/process_engine_core#199

**Changes:**

1. Throw an error, when an attempt to use `Mixed` or `Unspecified` Gateways is made.
2. Implement strict restrictions for Split- and Join Gateways. These are as follows:
    * the Split-Gateway must have only one incoming SequenceFlow and multiple outgoing SequenceFlows.
    * the Join-Gateway must have only one outgoing SequenceFlow and multiple incoming SequenceFlows.
3. Implement validations for `ExclusiveSplitGateways`, which will throw an error when:
    * No SequenceFlow with a truthy condition is attached
    * More than one SequenceFlow with a truthy condition is attached 
4. Increase test coverage for ParallelGateways and ExclusiveGateways to ensure that misconfigurations are handled properly.
5. Preserve the error codes of `@essential-projects` errors that can get thrown by the handlers.

**Issues:**

Closes #132 

PR: #137

## How can others test the changes?

Run the tests.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️      |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️      |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

File: test/1_process_engine/parallel_gateway_test.js [hunk 1]
```diff
@@ -13,15 +13,15 @@ describe('Parallel Gateway execution', () => {
...
+    const processDefFileList = ['parallel_gateway_test', 'parallel_gateway_unsupported_test'];
     await testFixtureProvider.importProcessFiles(processDefFileList);
   });
 
   after(async () => {
     await testFixtureProvider.tearDown();
   });
 
-  it('should successfully run two parallel tasks and contain the result of each task in the token history.', async () => {
+  it('should successfully run multiple parallel running branchs and return each result with the token.', async () => {
```
Comment (Vyperus) [inline test/1_process_engine/parallel_gateway_test.js]:
```suggestion
  it('should successfully run multiple parallel branches and return each result with the token.', async () => {
```
