### PR TITLE
🔒 ♻️ Validate UserTask payloads

### LINKED ISSUE #240: 🔒♻️ UserTask handlers require form field validation
#### Describe your issue

We have run into the following issue with the UserTask handlers:

When a UserTask with a FormField that requires a value from the `token` is used, it is possible that the ConsumerAPI's `getUserTask` queries will fail, if the token doesn't contain the expected values.

This is because the ConsumerAPI has to match the token history against the UserTask's expected FormField values.
If a token reference, like for example `token.current.a.b.c` fails, then the entire request will fail, since the UserTasks expectations cannot be fulfilled.

Failing the request is actually correct, because the UserTask is effectively unprocessable.

However, this has also the side effect of breaking the BPMN-Studio's `Active Task List`, because repeated polling against the endpoint will now always fail, until the UserTask is cleared up.  

#### How can others reproduce the issue?

- Deploy a Process that contains 2 tasks:
    - A ServiceTask that returns some sample token (ideally an empty object)
    - A UserTask with a FormField, that expects some value like `token.current.a.b.c`
- Running that Process will not be a problem. The UserTask gets suspended and waits to be processed
- Now try querying the UserTasks through the ConsumerAPI
    - This will now fail, because the UserTask's FormField can never be filled in.

#### Possible solution

We need to intercept this error right at the beginning, when the UserTask handler in `@process-engine/process_engine_core` is first started.
A validation function must be implemented, which compairs each FormField's token reference (if any) against the token passed to the UserTask. 
If such a validation fails, the UserTask must be persisted with an error and a corresponding `UnprocessableEntityError` must be thrown.

This way, the end user (in this case the BPMN Studio) will not be able to run into this issue in the first place and we now right a way if a UserTask's expectations may be unfulfillable.

EDIT:
We could also introduce a `failUserTask` route, that would allow a user to clear up a UserTask manually. 
The route would then change the UserTasks' state to `error` and interrupt the ProcessInstance.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### LINKED ISSUE #263: 🐛  ManualTask and UserTask Instances get suspended too soon
#### Describe your issue

The instances for ManualTasks and UserTasks get placed in a suspended state, before their subscriptions for the `onFinish` event have been created.

The time gap between the state change and the creation of the subscription is only minuscule, but it may be enough to cause trouble on automated systems that periodically poll and handle suspended tasks.

Our integrationtests are one such example. We currently have sporadic test failures for the `BoundaryEvent Chaining` tests on Jenkins. These tests work in exactly the same way as described above.

#### Possible Solution

We must ensure that the UserTask and ManualTask instances only get suspended after their event subscriptions were created.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by ElRaptorus**
**Changes:**

1. Fix an issue which caused ManualTasks and UserTasks to be suspended before they had created their subscriptions on the EventAggregator.
    - This could lead to situations, where a UserTaskHandler missed a `FinishUserTask` notification and remained suspended indefinitely.
2. Add validation for a UserTask's FormField expressions, to ensure a FormField doesn't attempt to use non-existing token values.
3. Fix ErrorEventDefinition parsing.

**Issues:**

Closes #240
Closes #263

PR: #271

## How can others test the changes?

Try executing a UserTask with a FormField, which tries accesing non-existing token values (like `${token.a.b.c.whatever}`).

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

### CODE REVIEW

File: test/1_process_engine/user_task_tests.js [hunk 1]
```diff
@@ -215,8 +215,40 @@ describe('UserTasks - ', () => {
...
+      should(error.message).be.match(errorMessage);
       should(error.code).be.equal(errorCode);
+    }
+  });
+
+  it('should fail to execute a UserTask containing a FormField with an invalid configuration.', async () => {
+
+    try {
+      const startEventId = 'StartEvent_2';
+      await testFixtureProvider.executeProcess(processModelId, startEventId);
```
Comment (Vyperus) [inline test/1_process_engine/user_task_tests.js]:
```suggestion

      await testFixtureProvider.executeProcess(processModelId, startEventId);
```
