### PR TITLE
✨ Add a Response when the User accesses the Root Route

### LINKED ISSUE #201: ✨ Provide a default output when accessing the root url of the ProcessEngine
#### Describe your issue

When accessing the Runtime by its base url, you will get an error. 
The error occurs, because there is no route registered in express that provides content to the root url.

This may be somewhat confusing for users who do not know this. They might think they have done something wrong when starting up the Runtime, when in fact it is working just fine.

#### How can others reproduce the issue?

- Start the runtime 
- Try accessing it in your browser under `localhost:8000` (or whichever port you use)
- See an error, saying `Cannot GET /`

#### Possible solution

It would be helpful to have some basic content being displayed here, to show a user that the Runtime is truly up and running.

We should add a new Router, specifically for the runtime, that returns some content for the user to see.

Ideally, this should be some kind of Welcome-Page, with instructions on how to use the Runtime through BPMN Studio.
But until a concept for such a page exists, a simple JSON with the following content will suffice:
- Application name
- Application version

These infos can be retrieved from the package.json.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by robpal94**
**Changes:**

1. Adds a response when the user tries to access the route route of a running ProcessEngine instance.

The answer returns some properties from the `package.json` such as: 
* The application name
* The current running version
* The license
* The contriburots

**Issues:**

Closes #201 

PR: #211

## How can others test the changes?

Start the application and access `localhost:8000`.
You should no longer receive `Cannot GET /`, but a formatted JSON that contains the properties listed above.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -74,6 +75,27 @@ async function startProcessEngine(sqlitePath) {
...
+        name: name,
+        version: version,
+        license: license,
+        contributors: contributors,
+      };
+
+      response
+        .status(200)
+        .header('Content-Type', 'application/json')
+        .send(JSON.stringify(returnObject, null, 2));
```
Comment (ElRaptorus) [inline index.js]: That's whats `response.json()` is for 😉 

```suggestion
response
  .status(200)
  .json(returnObject);
```
