### PR TITLE
🐛 Fix Join Gateway Finish Check

### LINKED ISSUE #389: 🐛 ParallelGateways warten nicht auf alle eingehende Pfade
## Description

Sobald zwei Token durch den selben Pfad gehen wird der Prozess beendet.
Scheinbar wird nur auf die Anzahl der Token mit der Anzahl der eingehenden Pfade gecheckt.

Screenshot 2019-08-12 at 16 38 16

## Reproduction

Siehe Screenshot

[parallelgatewaybug.bpmn.zip](https://github.com/process-engine/process_engine_runtime/files/3493029/parallelgatewaybug.bpmn.zip)

### PR DESCRIPTION
**Pull request by SteffenKn**
## Changes

1. Fix Join Gateway Finish Check

## Issues

Closes #389

PR: #398

### CODE REVIEW

File: test/1_process_engine/parallel_gateway_test.js [hunk 1]
```diff
@@ -122,6 +125,23 @@ describe('Parallel Gateway execution', () => {
...
+    const payload = {
+      correlationId: correlationId,
+    };
+    const returnOn = StartCallbackType.CallbackOnProcessInstanceFinished;
+
+    const result = await testFixtureProvider
+      .managementApiClient
+      .startProcessInstance(defaultIdentity, parallelGatewayFinishTestId, payload, returnOn);
+
+    should(result.tokenPayload).have.size(2, 'There should be two waiting manual tasks');
```
Comment (ElRaptorus) [inline test/1_process_engine/parallel_gateway_test.js]: Leftover:

```suggestion
    should(result.tokenPayload).have.size(2, 'There should be two entries in the final token payload!');
```
